### ISSUE TITLE
BMT: Save date for when workshop has been finished in database

### ISSUE THREAD

**Issue by ReedOnly** [equinor/fusion-bmt#474]
This is needed for #138

**Comment by hnformentin** [comment]
Isn't it need for #430 instead?
That would be great to have some additional description, if you have something else in mind let me know.
My guess so far is that it should be in the backend folder, so I am investigating :-)

**Comment by hnformentin** [comment]
Understanding the reference PR #452 
Backend:
- backend/api/GQL/Mutation.cs: what is the convention to use "_"?
- backend/api/Migrations/20210709134613_WorkshopSummary.Designer.cs and
 backend/api/Migrations/20210709134613_WorkshopSummary.cs: autogenerated files that enable compatibility between evaluations created earlier to the changes
- backend/api/Migrations/BmtDbContextModelSnapshot.cs: autogenerated file (1) when should product version be changed? (2) observe if a new Property called WorkshopCompleteDate was created, (3) why previousId was changed to previousIdId?, (4)
-
