### ISSUE TITLE
BMT: Allow to remove Facilitator on Nomination stage

### ISSUE THREAD

**Issue by achaikou** [equinor/fusion-bmt#479]
At the moment if user made a mistake and added someone they didn't want to add as a facilitator in nomination stage, it's impossible to remove them from the list as only non-facilitators get the privilege of Delete button. It's also impossible to edit person's role (to Participant, for example) as a workaround. The only solution to this situation is to create a new evaluation, which is not desirable especially if many people already were nominated.

Expected behavior is not clearly defined.

We always want to have at least one facilitator assigned to evaluation, but it's unclear if that always must be a person who created evaluation, or if it enough if there exists any person who is a facilitator [note that if person who created evaluation removes themselves from facilitators list they might lose edit rights and so on].

It also must be considered what should happen to the other person named facilitator aka what view/edit/removal rights should that person have to evaluation in Nomination stage.

**Comment by denektenina** [comment]
The following has been decided on:
* The user cannot delete his/herself, but can delete other facilitators.
* Thus, the original facilitator can be deleted by one of the other facilitators once they are added
