### ISSUE TITLE
Administrators should be able to copy an existing project type with all barriers and questions

### ISSUE THREAD

**Issue by lightenup** [equinor/fusion-bmt#522]
Questions and barriers should be duplicated to the new project type

- [ ] #604

<img width="1117" alt="add project type" src="https://user-images.githubusercontent.com/7236757/132224052-0c60e258-0c14-40c0-8c37-e2cd43bd4c0a.PNG">

**Comment by ReedOnly** [comment]
This will be replaced by #637 after discussion with costumers about using labels for sub projects instead of duplicating entire question set for each sub project type
