### ISSUE TITLE
Save data on navigation

### ISSUE THREAD

**Issue by achaikou** [equinor/fusion-bmt#538]
When I set "severity" indicator, and right after navigate to to a different barrier, my choice is not saved.
"Saving" indicator is on the other side of the field, so I pay no attention to it.
And anyway that's just not a good user experience? I don't even leave the page? Why would I expect that my data won't get saved?

The issue doesn't have to be about indicator, but any provided user input.

**Comment by lightenup** [comment]
We need Cypress tests for this

**Comment by denektenina** [comment]
Have we decided how to solve this? Is it enough to ensure the data is saved before switching barrier or should the confirmation be bigger / more obvious? Should we move away from autosave to a save-button again?

**Comment by ReedOnly** [comment]
I think ensuring the data is saved no matter if you navigate or not is what we need to achieve here. Don't think "Saved" confirmation needs to be bigger, and we do not want a save button for this behavior.
