### ISSUE TITLE
Cypress Tests: At nomination stage, add test for adding user through the UI. Verify that user is added (by logging in for example)

### ISSUE THREAD

**Issue by petterwildhagen** [equinor/fusion-bmt#590]

**Comment by hnformentin** [comment]
@petterwildhagen do you see this test placed in `nominations_spec`: 
https://github.com/equinor/fusion-bmt/blob/6647c7de0dd2512e81ce893b149785cbbc9aa532/frontend/cypress/integration/nominations_spec.ts#L52)?
