### ISSUE TITLE
Cypress Test: Verify capabilities offered to user not part of evaluation

### ISSUE THREAD

**Issue by petterwildhagen** [equinor/fusion-bmt#598]
A user that is not a member of an evaluation, aka an undefined participant, should be able to view the content of the evaluation which means that the user can:

click on the evaluation and not get an error
display the content of all of the tabs on all stages of the evaluation
click on an action, and display the content

The undefined user should not be able to:

answer any questions
add, edit or delete actions
add notes to actions
view the answers in the AnswerSummarySidebar
edit the workshop summary on the workshop stage
progress the evaluation to the next stage
check the complete switch on different stages of the evaluation

**Comment by hnformentin** [comment]
The PR has several tests into it, it should be split into several PR's to make review quicker.
@petterwildhagen could you specify in the issue where in the test structure you think this should reside?

**Comment by petterwildhagen** [comment]
@hnformentin 
click on the evaluation and not get an error
..> is adressed in landing page test

display the content of all of the tabs on all stages of the evaluation
..> not sure at the moment
click on an action, and display the content
..> be put into the actions tests & refactor the actions tests so that they reflect who can do what

The undefined user should not be able to:

answer any questions
..> We need to create new tests 'question_spec.ts' which are role based where this should go in.
add, edit or delete actions
..> extend existing actions tests.
add notes to actions
..> extend existing actions tests

view the answers in the AnswerSummarySidebar
..> extend actions tests
edit the workshop summary on the workshop stage
..> create new tests 'workshop summary.ts' that covers who can edit and not edit and put it in here
progress the evaluation to the next stage
..> this is part of the nomination tests
check the complete switch on different stages of the evaluation
..> Add this to tests for each stage that can be completed and make sure read only (undefined) cannot complete

**Comment by ReedOnly** [comment]
Covered by #873
