### ISSUE TITLE
Backend: Mutation to "delete" questionTemplate

### ISSUE THREAD

**Issue by ReedOnly** [equinor/fusion-bmt#608]
This should not delete questionTemplate but hide from active questionTemplate

**Comment by ErlendHaa** [comment]
What should this one do? Currently we have a chain of QuestionTemplates where only the most recent is "active".

If we delete the active QT, (which is the only one active to the user) should we also delete it's "predecessors" ?
Or should we just mark the QT as "Inactive", making the entire chain of revisions unreachable to the enduser (admin).

**Comment by ReedOnly** [comment]
As we talked about yesterday, I think the last point, marking QT as inactive and making it unreachable is the most correct way to do it for now!

**Comment by ErlendHaa** [comment]
For traceability we might want to introduce a new status. E.g:
```
public enum Status
{
    Active,
    Inactive, // QT is an old (archived) version of a QT
    Voided,   // QT is deleted
}
```
