### ISSUE TITLE
BMT: Move evaluation to different project:

### ISSUE THREAD

**Issue by eiriksanderfjeld** [equinor/fusion-bmt#989]
Hei 
Av en eller annen grunn kommer ikke de to siste Johan Sverdrup evalueringene opp og jeg har heller ingen måte å koble dem til prosjektet
 
 
 
![image](https://user-images.githubusercontent.com/32896188/152483122-0d036074-bdd6-4a79-847c-ceee319311b9.png)

**Comment by eiriksanderfjeld** [comment]
Evaluering opprettet under Johan Castberg og ikke Johan Sverdrup

**Comment by petterwildhagen** [comment]
One Johan Sverdup project is connected to the same fusion project id as a Castberg Project:
![image](https://user-images.githubusercontent.com/16671886/152505896-9aff1e20-3ccb-4c47-853d-0420b34e6e8c.png)

**Comment by petterwildhagen** [comment]
The other JS evaluation under Castberg is also linked to the same fusion  project id as the other castberg projects:
![image](https://user-images.githubusercontent.com/16671886/152506948-cabc207a-d3c3-4b31-9d64-8272f0f4f3c1.png)

The fusion project id for the castberg projects is:

 {
  "fusionProjectId": "64c6b27f-2978-4878-b298-b11b62c93c8d",

}

**Comment by petterwildhagen** [comment]
Since the evaluations are created under castberg this is where they will show up.
